build-deps:
  - flutter
  - clang
  - cmake
scripts:
  - flutter build linux
mapping:
  ainst.sh: /usr/bin/ainst
  ainst.desktop: /usr/share/applications/ainst.desktop
  assets/installer.png: /usr/share/icons/hicolor/512x512/apps/ainst.png
  build/linux/x64/release/bundle: /usr/share/ainst
