build-deps:
  - flutter
  - clang
  - cmake
scripts:
  - git config --global --add safe.directory /opt/flutter
  - sudo flutter build linux
mapping:
  ainst.sh: /usr/bin/ainst
  ainst.desktop: /usr/share/applications/ainst.desktop
  assets/logo.png: /usr/share/icons/hicolor/512x512/apps/ainst.png
  build/linux/x64/release/bundle: /usr/share/ainst
